In [1]:
import pandas as pd
import numpy as np

In [2]:
clientes = pd.read_csv(
    "../data/processed/clientes_clean.csv"
)

productos = pd.read_csv(
    "../data/processed/productos_clean.csv"
)

transacciones = pd.read_csv(
    "../data/processed/transacciones_clean.csv"
)

conversaciones = pd.read_csv(
    "../data/processed/conversaciones_clean.csv"
)

In [3]:
transacciones["fecha_hora"] = pd.to_datetime(
    transacciones["fecha_hora"]
)

In [4]:
# FEATURING ENGINE

In [5]:
# FEATURE 1 - GASTO TOTAL
gasto_total = (
    transacciones.groupby("user_id")["monto"]
    .sum()
)

In [6]:
# FEATURE 2 - GASTO PROMEDIO
gasto_promedio = (
    transacciones.groupby("user_id")["monto"]
    .mean()
)

In [7]:
# FEATURE 3 — NÚMERO DE TRANSACCIONES
num_transacciones = (
    transacciones.groupby("user_id")
    .size()
)

In [8]:
# FEATURE 4 — CATEGORÍA FAVORITA
categoria_favorita = (
    transacciones.groupby("user_id")["categoria_mcc"]
    .agg(lambda x: x.value_counts().index[0])
)

In [9]:
# FEATURE 5 — CASHBACK TOTAL
cashback_total = (
    transacciones.groupby("user_id")["cashback_generado"]
    .sum()
)

In [10]:
# FEATURE 6 — TRANSACCIONES INTERNACIONALES
internacionales = (
    transacciones.groupby("user_id")["es_internacional"]
    .sum()
)

In [11]:
# FEATURE 7 — TRANSACCIONES ATÍPICAS
atipicas = (
    transacciones.groupby("user_id")["patron_uso_atipico"]
    .sum()
)

In [12]:
# DATA SET FINAAAAAL

In [13]:
features = pd.DataFrame({
    "gasto_total": gasto_total,
    "gasto_promedio": gasto_promedio,
    "num_transacciones": num_transacciones,
    "categoria_favorita": categoria_favorita,
    "cashback_total": cashback_total,
    "transacciones_internacionales": internacionales,
    "transacciones_atipicas": atipicas
})

In [15]:
# RESULTADOS
features.head()

,gasto_total,gasto_promedio,num_transacciones,categoria_favorita,cashback_total,transacciones_internacionales,transacciones_atipicas
user_id,,,,,,,
USR-00001,119570.59,2135.189107,56,servicios_digitales,122.33,2,0
USR-00002,212722.67,2874.630676,74,transferencia,147.08,1,0
USR-00003,190801.09,2415.203671,79,transferencia,165.43,4,0
USR-00004,580113.74,8789.602121,66,transferencia,0.00,2,0
USR-00005,190277.30,2045.992473,93,transferencia,162.99,1,0

In [16]:
features.head()

,gasto_total,gasto_promedio,num_transacciones,categoria_favorita,cashback_total,transacciones_internacionales,transacciones_atipicas
user_id,,,,,,,
USR-00001,119570.59,2135.189107,56,servicios_digitales,122.33,2,0
USR-00002,212722.67,2874.630676,74,transferencia,147.08,1,0
USR-00003,190801.09,2415.203671,79,transferencia,165.43,4,0
USR-00004,580113.74,8789.602121,66,transferencia,0.00,2,0
USR-00005,190277.30,2045.992473,93,transferencia,162.99,1,0

In [17]:
features.info()

<class 'pandas.DataFrame'>
Index: 15025 entries, USR-00001 to USR-15025
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   gasto_total                    15025 non-null  float64
 1   gasto_promedio                 15025 non-null  float64
 2   num_transacciones              15025 non-null  int64
 3   categoria_favorita             15025 non-null  str
 4   cashback_total                 15025 non-null  float64
 5   transacciones_internacionales  15025 non-null  int64
 6   transacciones_atipicas         15025 non-null  int64
dtypes: float64(3), int64(3), str(1)
memory usage: 939.1+ KB

In [18]:
features.describe()

,gasto_total,gasto_promedio,num_transacciones,cashback_total,transacciones_internacionales,transacciones_atipicas
count,1.502500e+04,15025.000000,15025.000000,15025.000000,15025.000000,15025.000000
mean,3.261414e+05,5980.839221,53.391880,177.727953,2.662429,2.761065
std,2.368850e+05,3423.871071,23.003222,368.544838,1.933806,12.972759
min,2.405350e+03,445.353333,5.000000,0.000000,0.000000,0.000000
25%,1.543477e+05,3289.694713,39.000000,0.000000,1.000000,0.000000
50%,2.436138e+05,4706.420847,56.000000,0.000000,2.000000,0.000000
75%,4.972572e+05,8400.796308,68.000000,206.590000,4.000000,0.000000
max,1.508073e+06,21289.530968,100.000000,8540.160000,13.000000,100.000000

In [19]:
features.to_csv(
    "../data/processed/features.csv",
    index=True
)